{"id":1,"totalCount":1,"businessName":"Žvaigždūnė Tvarijonaitė","addressLine1":"Vilniaus g. 11, ","addressLine2":"Kaunas, ","addressLine3":"LT-10849","businessCompID":"123456789","invoiceNumber":"CAR-21 NR.031","contractNumber":"ĄąČčĘęĖėĮįŠšŲųŪūŽž /55/CAR-21-Nr.031/2021","serviceDescription":"Car invoicing","expenseAmount":782.09} 
